---
abstract: 'Provide CRUD functionality to your Controllers'
author:
  - 'David Schmidt <davewood@cpan.org>'
build_requires:
  Catalyst: 0
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::ScriptRunner: 0
  Catalyst::Test: 0
  Catalyst::View::TT: 0
  DBIx::Class: 0
  DBIx::Class::Schema: 0
  FindBin: 0
  HTML::FormHandler::Model::DBIC: 0
  HTML::FormHandler::Moose: 0
  HTTP::Request::Common: 0
  Test::Exception: 0
  Test::Moose: 0
  Test::More: 0
  Test::UseAllModules: 0
  URI: 0
  base: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CatalystX-Resource
requires:
  Catalyst::Controller: 0
  CatalystX::Component::Traits: 0
  CatalystX::InjectComponent: 0
  Moose: 0
  Moose::Role: 0
  MooseX::MethodAttributes::Role: 0
  MooseX::Types::Common::String: 0
  MooseX::Types::LoadableClass: 0
  MooseX::Types::Moose: 0
  namespace::autoclean: 0
version: 0.01
