---
abstract: 'Provide CRUD functionality to your Controllers'
author:
  - 'David Schmidt <davewood@cpan.org>'
build_requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::File: 0
  Catalyst::View::TT: 0
  File::Temp: 0
  FindBin: 0
  HTTP::Message: 0
  Test::Exception: 0
  Test::More: 0.88
  Test::UseAllModules: 0
  URI: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CatalystX-Resource
requires:
  Catalyst::ActionRole::MatchRequestMethod: 0
  Catalyst::Controller::ActionRole: 0
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::Plugin::Session: 0.27
  Catalyst::Runtime: 5.80013
  CatalystX::InjectComponent: 0
  DBIx::Class: 0
  HTML::FormHandler: 0
  HTML::FormHandler::Model::DBIC: 0
  Moose: 0
  MooseX::MethodAttributes: 0
  MooseX::Types: 0
  MooseX::Types::Common: 0
  MooseX::Types::LoadableClass: 0
  namespace::autoclean: 0
resources:
  homepage: https://github.com/davewood/catalystx-resource
  repository: https://github.com/davewood/catalystx-resource.git
version: 0.003_002
